### ISSUE TITLE
JSAPI.emit.error {code:6000003,message:"appID invalid"}

### ISSUE THREAD

**Issue by risingmax123456** [ZEGOCLOUD/zego_uikit_prebuilt_live_streaming_rn#2]
Facing issue when start live stream

Console print are

########cacheAudioVideoUserList######## null
 LOG  #########Timer: First render initializes and clears timer undefined undefined
 LOG  ZEGOUIKit[INFO]:  [ZegoUIKitCorePlugin][installPlugins]Plugin install success, plugin: ZIM
 LOG  ZEGOUIKit[INFO]:  [ZegoUIKitCorePlugin][getPlugin] type:  1
 LOG  ZEGOUIKit[INFO]:  [ZegoUIKitCorePlugin][getPlugin] type:  1
 LOG  SignalingPlugin[INFO]:  [Core]ZegoSignalingPluginCore successful instantiation.
 LOG  SignalingPlugin[INFO]:  [Core]Create zim success.
 LOG  SignalingPlugin[INFO]:  [Core]Unregister callback from ZIM...
 LOG  SignalingPlugin[INFO]:  [Core]Register callback for ZIM...
 LOG  SignalingPlugin[INFO]:  [ZegoPluginUserInRoomAttributesCore]Unregister callback from ZIM...
 LOG  SignalingPlugin[INFO]:  [ZegoPluginUserInRoomAttributesCore]Register callback for ZIM...
 LOG  SignalingPlugin[INFO]:  [ZegoPluginRoomPropertiesCore]Unregister callback from ZIM...
 LOG  SignalingPlugin[INFO]:  [ZegoPluginRoomPropertiesCore]Register callback for ZIM...
 LOG  SignalingPlugin[INFO]:  [ZegoPluginRoomMessageCore]Unregister callback from ZIM...
 LOG  SignalingPlugin[INFO]:  [ZegoPluginRoomMessageCore]Register callback for ZIM...
 LOG  ######layoutHandle {"height": 0, "width": 0, "x": 363, "y": 567}
 LOG  JSAPI.emit.connectionStateChanged {extendedData:"{}",event:1,state:1}
 LOG  SignalingPlugin[INFO]:  [Core]Connection state changed, state:1, event:1, extended data:{}
 LOG  JSAPI.emit.error {code:6000003,message:"appID invalid"}
 ERROR  SignalingPlugin[ERROR]:  [Core]Zim error, code:6000003, message:appID invalid.

any help ?

**Comment by kaelding** [comment]
Please refer our document.
https://docs.zegocloud.com/article/14924

**Comment by risingmax123456** [comment]
I follow same documentation code still facing issue

//import liraries
import React, { useRef } from 'react';
import { View, } from 'react-native';
import styles from './GoLiveStreamingStyle';
import ZegoUIKitPrebuiltLiveStreaming, { HOST_DEFAULT_CONFIG, ZegoMenuBarButtonName } from '@zegocloud/zego-uikit-prebuilt-live-streaming-rn'
import * as ZIM from 'zego-zim-react-native';

// create a component
const GoLiveStreaming = (props) => {
    const prebuiltRef = useRef()
    return (
        <View style={styles.container}>
            <ZegoUIKitPrebuiltLiveStreaming
                ref={prebuiltRef}
                appID={'*********'}
                appSign={'***************'}
                userID={"test1"}
                userName={"test"}
                liveID={"test789"}

                config={{
                    ...HOST_DEFAULT_CONFIG,
                    onLeaveLiveStreaming: () => { props.navigation.navigate.goBack() },

                    onStartLiveButtonPressed: () => { console.log('########HostPage onStartLiveButtonPressed'); },
                    onLiveStreamingEnded: () => {
                        console.log('########HostPage onLiveStreamingEnded');
                    },
                    onLeaveLiveStreaming: () => {
                        console.log('########HostPage onLeaveLiveStreaming');
                        props.navigation.navigate('HomePage');
                    },
                    durationConfig: {
                        isVisible: true,
                        onDurationUpdate: (duration) => {
                            console.log('########HostPage onDurationUpdate', duration);
                            if (duration === 10 * 60) {
                                prebuiltRef.current.leave();
                            }
                        }
                    },
                    topMenuBarConfig: {
                        buttons: [ZegoMenuBarButtonName.minimizingButton, ZegoMenuBarButtonName.leaveButton],
                    },

                }}
                plugins={[ZIM]}
            />
        </View>
    );
};

//make this component available to the app
export default GoLiveStreaming;

**Comment by yoer** [comment]
Have you applied for an appID in our [ZEGOCLOUD Admin Console](https://console.zegocloud.com/)?

**Comment by risingmax123456** [comment]
Issue fixed (App ID need to be integer)
